import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AppShell, PageHeader } from "@/components/app-shell";
import { Badge, Card } from "@/components/ui-bits";
import { teamAnalyticsService, type DeveloperDetails } from "@/lib/team-analytics-service";
import { ArrowLeft, Loader2 } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

export const Route = createFileRoute("/team/developers/$id")({ head: () => ({ meta: [{ title: "Developer Analytics · GitInsight AI" }] }), component: DeveloperDetailsPage });
function DeveloperDetailsPage() {
  const { id } = Route.useParams(); const [developer, setDeveloper] = useState<DeveloperDetails | null>(null);
  useEffect(() => { const repository = new URLSearchParams(window.location.search).get("repository"); if (repository) teamAnalyticsService.getDeveloperDetails(id, repository).then(setDeveloper).catch(() => setDeveloper(null)); }, [id]);
  if (!developer) return <AppShell><div className="grid place-items-center py-24"><Loader2 className="h-7 w-7 animate-spin text-brand" /></div></AppShell>;
  const summary = [["Commits", developer.commits], ["Pull Requests", developer.pullRequests], ["Merged PRs", developer.mergedPullRequests], ["Issues", developer.issues], ["Reviews", developer.reviews], ["Code Changes", developer.codeChanges.toLocaleString()]];
  return <AppShell><Link to="/team" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-5"><ArrowLeft className="h-4 w-4" /> Back to Team Analytics</Link><PageHeader title={developer.name} subtitle={`@${developer.username} · ${developer.role}`} /><div className="flex items-center gap-4 mb-6"><div className="h-16 w-16 rounded-full bg-brand-gradient text-white grid place-items-center text-xl font-semibold">{developer.avatar}</div><div><div className="text-3xl font-semibold">{developer.score}<span className="text-sm text-muted-foreground"> / 100 performance score</span></div><Badge tone="brand">{developer.grade}</Badge></div></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6 mb-6">{summary.map(([label, value]) => <Card key={label} className="p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-2 text-xl font-semibold">{value}</div></Card>)}</div><div className="grid gap-5 lg:grid-cols-2"><Card className="p-6"><div className="font-semibold mb-4">Contribution activity</div><div className="h-64"><ResponsiveContainer><BarChart data={developer.activity}><CartesianGrid stroke="var(--color-border)" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" /><YAxis /><Tooltip /><Bar dataKey="commits" fill="var(--color-brand)" /><Bar dataKey="pullRequests" fill="var(--color-brand-2)" /><Bar dataKey="reviews" fill="var(--color-accent-cyan)" /></BarChart></ResponsiveContainer></div></Card><Card className="p-6"><div className="font-semibold mb-4">Performance factors</div>{developer.scoreFactors.map((factor) => <div key={factor.label} className="mb-4"><div className="flex justify-between text-sm"><span>{factor.label}</span><span>{factor.value}/{factor.weight}</span></div><div className="mt-1 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-brand-gradient" style={{ width: `${(factor.value / factor.weight) * 100}%` }} /></div></div>)}<p className="mt-5 text-xs text-muted-foreground">{developer.insight}</p></Card><Card className="p-6 lg:col-span-2"><div className="font-semibold mb-4">Code, reviews, and issue activity</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Additions", developer.additions], ["Deletions", developer.deletions], ["Files changed", developer.filesChanged], ["PR merge time", `${developer.mergeTimeHours}h`], ["Review response", `${developer.responseTimeHours}h`], ["Open issues", developer.openIssues], ["Closed issues", developer.closedIssues], ["PR comments", developer.prComments]].map(([label, value]) => <div key={label} className="rounded-xl bg-muted/60 p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-2 font-semibold">{value}</div></div>)}</div></Card></div></AppShell>;
}
